services:
  api:
    build: .
    container_name: fastapi_project
    ports:
      - "8000:8000"
    environment:
      DB_USERNAME: "project"
      DB_PASSWORD: "project"
      DB_NAME: "project"
      DB_HOST: "db:5432"
    depends_on:
      - db
    command: fastapi run src/main.py --port 8000

  db:
    image: postgres:17
    container_name: postgres_project
    environment:
      POSTGRES_USER: "project"
      POSTGRES_PASSWORD: "project"
      POSTGRES_DB: "project"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
